### ISSUE TITLE
A how-to instantiate a dialog between two devices with hybrid encryption enabled 

### ISSUE THREAD

**Issue by zsavely** [google/tink#116]
Is there a guide or a sample code that allows to create private and public keys on two different devices, then exchange these public keys and then establish a communication between these two devices?

**Comment by thaidn** [comment]
Hi zsavely,

If you want to build a secure channel, you might want to consider using a TLS library. At the moment Tink is more suitable for encrypting data at rest.

**Comment by zsavely** [comment]
Hi thaidn, 

Thank you for your reply.

If I get this right, TLS is for live connection? But I need a some kind of a PGP encryption. I thought this Hybrid approach that you have in the library could solve the issue.

**Comment by zsavely** [comment]
So basically I need thishttps://github.com/google/capillary. But I don't want it to be so 'frameworky'.

**Comment by thaidn** [comment]
We haven't developed a PGP-like primitive yet. Our hybrid encryption primitive may be inadequate because it doesn't provide authenticity (e.g., the receiver wouldn't know the identity of the sender), it looks like what you need is authenticated public key encryption. We have a plan to add this primitive, but it is not a priority at the moment. What's your timeline?

**Comment by zsavely** [comment]
Authenticity will be provided in a different way in my case, so probably hybrid encryption is the option I would consider, but I don't see a way to communicate with a peer. Do I need to share a public key, so that another peer will encrypt a message with it?

**Comment by zsavely** [comment]
By the way, when executing this code,
```kotlin
 AndroidKeysetManager.Builder()
        .withSharedPref(this, TINK_KEYSET_NAME, PREF_FILE_NAME)
        .withKeyTemplate(HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM)
        .withMasterKeyUri(MASTER_KEY_URI)
        .build()
        .getKeysetHandle()
```
I get this stack trace:
```log
09-06 18:00:11.700 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.szagurskii.testproject, PID: 30400
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.szagurskii.testproject/com.example.szagurskii.testproject.MainActivity2}: java.security.GeneralSecurityException: The keyset contains a non-private key
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.security.GeneralSecurityException: The keyset contains a non-private key
        at com.google.a.a.n.a(KeysetHandle.java:163)
        at com.google.a.a.n.c(KeysetHandle.java:153)
        at com.example.szagurskii.testproject.MainActivity2.onCreate(MainActivity2.kt:87)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
```
So is there a way to initialize `HybricKeysetHandle` on Android?

**Comment by thaidn** [comment]
> Authenticity will be provided in a different way in my case, so probably hybrid encryption is the option I would consider, but I don't see a way to communicate with a peer. Do I need to share a public key, so that another peer will encrypt a message with it?

Yes, you'd need to share a public keyset. You can do that by generating a private keyset (your snippet is a correct to do that), then calling getPublicKeysetHandle on the keyset handle of the private keyset.

>  AndroidKeysetManager.Builder()
        .withSharedPref(this, TINK_KEYSET_NAME, PREF_FILE_NAME)
        .withKeyTemplate(HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM)
        .withMasterKeyUri(MASTER_KEY_URI)
        .build()
        .getKeysetHandle()

This generates a private keyset, and shouldn't throw the exception that you reported. The exception should happen only when you called KeysetHandle.getPublicKeysetHandle() on a keyset that contains a non-private key.
