### ISSUE TITLE
Crash on Android (API level 21)

### ISSUE THREAD

**Issue by Fi5t** [google/tink#152]
When I run my application with Tink under Android Lollipop (API 21), I face exception `java.security.NoSuchAlgorithmException: KeyGenerator AES implementation not found`.

```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{<my_secret_application>}: java.security.NoSuchAlgorithmException: KeyGenerator AES implementation not found
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.security.NoSuchAlgorithmException: KeyGenerator AES implementation not found
        at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:190)
        at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:183)
        at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:164)
        at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:135)
        at com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.generateNewAeadKey(AndroidKeystoreKmsClient.java:141)
        at com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getOrGenerateNewAeadKey(AndroidKeystoreKmsClient.java:128)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.withMasterKeyUri(AndroidKeysetManager.java:157)
----- cut-----
```

**Comment by thaidn** [comment]
Are you using Tink 1.2.0? This is a known issue, should be fixed at HEAD. We're going to release 1.2.1 which should include the fix.

@chuckx

**Comment by Fi5t** [comment]
Yeah, I'm using 1.2.0. When you going to roll out the release 1.2.1?

**Comment by chuckx** [comment]
I have one more commit I'm integrating into the 1.2 branch and will make time to preform the 1.2.1 release this week.

**Comment by chuckx** [comment]
Sorry about the delay. We had a hiccup with facilitating the full release process for a patch release that we're working around for 1.2.1. On top of that, I had a personal issue come up last weekend which derailed this week for me. I'm tackling a couple of hand off tasks right now and hope to have the release completed ASAP. Moving forward, future releases will be much easier to tackle and will be turned around in a much more timely fashion.

**Comment by thaidn** [comment]
1.2.1 is out. Please try and reopen this bug if you still encounter this issue. Thanks!
