### ISSUE TITLE
conflicts with 'com.google.protobuf:protobuf-java:3.6.1'

### ISSUE THREAD

**Issue by hereisderek** [google/tink#172]
my project depends on 'com.google.protobuf:protobuf-java:3.6.1', and it's causing conflits with tink

error at compile:

```
AGPBI: {"kind":"error","text":"Program type already present: com.google.protobuf.AbstractMessageLite","sources":[{}],"tool":"D8"}
> Task :frsipMobile:buildInfoGeneratorDebug
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':frsipMobile:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/derek/Workspace/.../.jar

```

if I try to exclude protobuf-lite from tink end up with runtime crash

```
    implementation ('com.google.crypto.tink:tink-android:1.2.1'){
        exclude group: 'com.google.protobuf', module: 'protobuf-lite'
    }
```

```

2019-01-11 19:01:42.894 29864-29864/com.deltapath.frsipMobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.deltapath.frsipMobile, PID: 29864
    java.lang.ExceptionInInitializerError
        at com.google.crypto.tink.aead.AeadConfig.<clinit>(AeadConfig.java:53)
        at com.google.crypto.tink.aead.AeadConfig.register(AeadConfig.java:138)
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto.<init>(TinkCrypto.kt:32)
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto.<init>(TinkCrypto.kt:27)
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto$Companion$singletonHolder$2.invoke(TinkCrypto.kt:54)
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto$Companion$singletonHolder$2.invoke(TinkCrypto.kt:54)
        at com.deltapath.frsiplibrary.custom.views.SingletonHolder.getInstance(SingletonHolder.kt:22)
        at com.deltapath.frsiplibrary.utilities.crypto.Cryptor$Companion.getDefaultCryptor(FrsipCrypto.kt:87)
        at com.deltapath.frsiplibrary.utilities.crypto.FrsipCrypto$Companion.getDefaultCryptoWithSharedPref(FrsipCrypto.kt:134)
        at com.deltapath.frsiplibrary.profile.Profile.init(Profile.java:45)
        at com.deltapath.frsiplibrary.profile.Profile.getSharedPreferences(Profile.java:74)
        at com.deltapath.frsiplibrary.profile.Profile.getUsername(Profile.java:179)
        at com.deltapath.frsiplibrary.profile.Profile.isEmpty(Profile.java:119)
        at com.deltapath.frsiplibrary.applications.FrsipApplication.onCreate(FrsipApplication.java:69)
        at com.deltapath.messaging.application.MessagingApplication.onCreate(MessagingApplication.java:74)
        at org.linphone.RootApplication.onCreate(RootApplication.java:111)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.UnsupportedOperationException
        at com.google.crypto.tink.proto.KeyTypeEntry.dynamicMethod(KeyTypeEntry.java:788)
        at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:336)
        at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:1514)
        at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:258)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:433)
        at com.google.crypto.tink.Config.getTinkKeyTypeEntry(Config.java:56)
        at com.google.crypto.tink.mac.MacConfig.<clinit>(MacConfig.java:49)
        at com.google.crypto.tink.aead.AeadConfig.<clinit>(AeadConfig.java:53) 
        at com.google.crypto.tink.aead.AeadConfig.register(AeadConfig.java:138) 
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto.<init>(TinkCrypto.kt:32) 
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto.<init>(TinkCrypto.kt:27) 
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto$Companion$singletonHolder$2.invoke(TinkCrypto.kt:54) 
        at com.deltapath.frsiplibrary.utilities.crypto.TinkCrypto$Companion$singletonHolder$2.invoke(TinkCrypto.kt:54) 
        at com.deltapath.frsiplibrary.custom.views.SingletonHolder.getInstance(SingletonHolder.kt:22) 
        at com.deltapath.frsiplibrary.utilities.crypto.Cryptor$Companion.getDefaultCryptor(FrsipCrypto.kt:87) 
        at com.deltapath.frsiplibrary.utilities.crypto.FrsipCrypto$Companion.getDefaultCryptoWithSharedPref(FrsipCrypto.kt:134) 
        at com.deltapath.frsiplibrary.profile.Profile.init(Profile.java:45) 
        at com.deltapath.frsiplibrary.profile.Profile.getSharedPreferences(Profile.java:74) 
        at com.deltapath.frsiplibrary.profile.Profile.getUsername(Profile.java:179) 
        at com.deltapath.frsiplibrary.profile.Profile.isEmpty(Profile.java:119) 
        at com.deltapath.frsiplibrary.applications.FrsipApplication.onCreate(FrsipApplication.java:69) 
        at com.deltapath.messaging.application.MessagingApplication.onCreate(MessagingApplication.java:74) 
        at org.linphone.RootApplication.onCreate(RootApplication.java:111) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
2019-01-11 19:01:42.895 29864-29869/com.deltapath.frsipMobile I/zygote: Do partial code cache collection, code=31KB, data=27KB
2019-01-11 19:01:42.895 29864-29869/com.deltapath.frsipMobile I/zygote: After code cache collection, code=31KB, data=27KB
2019-01-11 19:01:42.895 29864-29869/com.deltapath.frsipMobile I/zygote: Increasing code cache capacity to 128KB
```

**Comment by thaidn** [comment]
You cannot/should not use Protobuf Java on Android. You want to use Protobuf Lite. This is one of the reasons Tink provides two flavors Java and Android.

**Comment by hereisderek** [comment]
I'm not really sure the differences between protobuf java and lite, however swapping protobuf-java with lite results in 50+ compile error, seems to be a lot of missing classes

the project is currently setup using profobuf java, 
so what's the impact if I use com.google.crypto.tink:tink:1.2.1 on android?

**Comment by thaidn** [comment]
It is not recommended, but you can try.

I think you should rebuild the other project to use protobuf lite when runs on Android.

**Comment by hereisderek** [comment]
I ended up compiling tink-android against protobuf-java. that resolved any gradle conflicts with no obvious problem.

thanks for the reply @thaidn

**Comment by tuancoltech** [comment]
> I ended up compiling tink-android against protobuf-java. that resolved any gradle conflicts with no obvious problem.
> 
> thanks for the reply @thaidn

Hi @hereisderek , can you open-source the project that you already built **tink** against protobuf-java?
Thanks.

**Comment by CapnSpellcheck** [comment]
My org also uses protobuf-java on an ANdroid project. I am now trying to use ANdroidx crypto. @thaidn Google says on their protobuf README.md that using protobuf-java on Android is permitted:

> Note that in order to achieve maximum performance and code size, we will NOT guarantee API/ABI stability for Java Lite. If this is not acceptable for your use-case, please use the full Java runtime instead. Note that the latest version of Java Lite is not compatible with the 3.0.0 version.

Just curious, what is the recommended from solution from Google in consideration that protobuf states the above?

Is it possible to rewrite all classes in protobuf-lite to something else while also changing those class references in tink jar?
