### ISSUE TITLE
Go signature example doesn't work (fails roundtrip)

### ISSUE THREAD

**Issue by mightyguava** [google/tink#197]
I'm trying to follow the signature example in the [Golang howto guide](https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#signature), using `master`. It's failing with an interface conversion panic.

```
panic: interface conversion: *signature.ECDSASigner is not tink.Verifier: missing method Verify

goroutine 1 [running]:
github.com/google/tink/go/signature.(*verifierSet).Verify(0xc0000ec028, 0xc0000c0140, 0x4d, 0x50, 0xc0000ca200, 0x1c, 0x1c, 0x0, 0x0)
	/Users/yunchiluo/Development/go/pkg/mod/github.com/google/tink@v1.2.1-0.20190321234318-ba64189ae1a4/go/signature/verifier_factory.go:79 +0x1f1
main.main()
	/Users/yunchiluo/Development/tinkbug/main.go:31 +0x2f1
```

Complete code below
```go
package main

import (
	"log"

	"github.com/google/tink/go/keyset"
	"github.com/google/tink/go/signature"
)

func main() {
	kh, err := keyset.NewHandle(signature.ECDSAP256KeyTemplate()) // other key templates can also be used
	if err != nil {
		log.Fatal(err)
	}

	s, err := signature.NewSigner(kh)
	if err != nil {
		log.Fatal(err)
	}

	a, err := s.Sign([]byte("this data needs to be signed"))
	if err != nil {
		log.Fatal(err)
	}

	v, err := signature.NewVerifier(kh)
	if err != nil {
		log.Fatal(err)
	}

	if err := v.Verify(a, []byte("this data needs to be signed")); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by mightyguava** [comment]
Ah, looks like you now need to convert the private keyset handle to a public one and use that for the verifier. The error message is very unintuitive.

```
-	v, err := signature.NewVerifier(kh)
+
+	pubkh, err := kh.Public()
+	if err != nil {
+		log.Fatal(err)
+	}
+	v, err := signature.NewVerifier(pubkh)
```

**Comment by chuckx** [comment]
Thanks for calling this out.

I'm preparing a commit to update the howto to clean up all of the code
examples and in the process found a bug as well.
