### ISSUE TITLE
Android API 23 fails to round trip AES256_GCM_HKDF_4KB for particular buffer write combinations

### ISSUE THREAD

**Issue by mark-buer** [google/tink#229]
Hello,

While using the `androidx.security:security-crypto` library I stumbled onto an interesting bug.

When streaming with `AES256_GCM_HKDF_4KB` on Android API 23, certain combinations of write buffer sizes result in encrypted bytes that cannot be decrypted. I originally raised a bug for  this against the [security-crypto](https://issuetracker.google.com/issues/136693238) library, but after more investigation I believe that tink is where the issue might best be resolved.

Here is a minimal reproduction case:
(`androidx.security:security-crypto:1.0.0-alpha02` & `com.google.crypto.tink:tink-android:1.2.2`)

```java
import android.os.Bundle;
import android.util.Log;

import androidx.appcompat.app.AppCompatActivity;
import androidx.security.crypto.MasterKeys;

import com.google.crypto.tink.KeysetHandle;
import com.google.crypto.tink.StreamingAead;
import com.google.crypto.tink.config.TinkConfig;
import com.google.crypto.tink.integration.android.AndroidKeysetManager;
import com.google.crypto.tink.streamingaead.StreamingAeadFactory;
import com.google.crypto.tink.streamingaead.StreamingAeadKeyTemplates;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.security.GeneralSecurityException;
import java.util.Arrays;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            exerciseBug();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (GeneralSecurityException e) {
            e.printStackTrace();
        }
    }

    private void exerciseBug() throws IOException, GeneralSecurityException {
        String masterKeyAlias = MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC);

        TinkConfig.register();

        KeysetHandle streadmingAeadKeysetHandle = new AndroidKeysetManager.Builder()
                .withKeyTemplate(StreamingAeadKeyTemplates.AES256_GCM_HKDF_4KB)
                .withSharedPref(this, "__androidx_security_crypto_encrypted_file_keyset__", "__androidx_security_crypto_encrypted_file_pref__")
                .withMasterKeyUri("android-keystore://" + masterKeyAlias)
                .build().getKeysetHandle();

        StreamingAead streamingAead = StreamingAeadFactory.getPrimitive(streadmingAeadKeysetHandle);

        testWritingBuffersOfSizes(streamingAead, 4040); // okay
        testWritingBuffersOfSizes(streamingAead, 4040, 1); // fail
        testWritingBuffersOfSizes(streamingAead, 4040, 0); // okay
        testWritingBuffersOfSizes(streamingAead, 4039, 1); // okay
        testWritingBuffersOfSizes(streamingAead, 4039, 1, 0); // okay
        testWritingBuffersOfSizes(streamingAead, 4039, 1, 1); // fail
        testWritingBuffersOfSizes(streamingAead, 4041); // okay
        testWritingBuffersOfSizes(streamingAead, 8120, 1); // fail
        testWritingBuffersOfSizes(streamingAead, 12200, 1); // fail, and so on for any size given by 4080 * N + 4040
    }

    private void testWritingBuffersOfSizes(StreamingAead streamingAead, int... bufferSizes) throws GeneralSecurityException, IOException {
        // Encrypt some zero filled buffers
        byte[] cryptBytes;
        {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            try (OutputStream encryptingStream = streamingAead.newEncryptingStream(outputStream, new byte[]{42})) {
                for (int bufferSize : bufferSizes) {
                    byte[] buffer = new byte[bufferSize];
                    encryptingStream.write(buffer);
                }
            }
            cryptBytes = outputStream.toByteArray();
        }

        // Try to decrypt it
        {
            InputStream inputStream = new ByteArrayInputStream(cryptBytes);
            try (InputStream decryptingStream = streamingAead.newDecryptingStream(inputStream, new byte[]{42})) {
                byte[] buffer = new byte[16384];
                while (true) {
                    int bytesRead = decryptingStream.read(buffer);
                    if (bytesRead == -1) {
                        break;
                    }
                }
                Log.d("tink23bug", "okay with writes of sizes: " + Arrays.toString(bufferSizes));
            } catch (IOException e) {
                Log.e("tink23bug", "fail with writes of sizes: " + Arrays.toString(bufferSizes), e);
            }
        }
    }
}
```

Output:

```
okay with writes of sizes: [4040]
fail with writes of sizes: [4040, 1]
    java.io.IOException: No matching key found for the ciphertext in the stream.
        at com.google.crypto.tink.streamingaead.InputStreamDecrypter.read(InputStreamDecrypter.java:187)
        at com.google.crypto.tink.streamingaead.InputStreamDecrypter.read(InputStreamDecrypter.java:130)
        at com.markbuer.tink23bug.MainActivity.testWritingBuffersOfSizes(MainActivity.java:84)
        at com.markbuer.tink23bug.MainActivity.exerciseBug(MainActivity.java:54)
        at com.markbuer.tink23bug.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
okay with writes of sizes: [4040, 0]
okay with writes of sizes: [4039, 1]
okay with writes of sizes: [4039, 1, 0]
fail with writes of sizes: [4039, 1, 1]
    java.io.IOException: No matching key found for the ciphertext in the stream.
    <snip>
okay with writes of sizes: [4041]
fail with writes of sizes: [8120, 1]
    java.io.IOException: No matching key found for the ciphertext in the stream.
    <snip>
fail with writes of sizes: [12200, 1]
    java.io.IOException: No matching key found for the ciphertext in the stream.
    <snip>
```

This reliably fails for me when run any of the Android API level 23 emulator images (created via Android Studio). I have also reproduced this on the only API level 23 physical device we have available for testing. API level 24 seems okay, as does 28 (and I'd guess the ones between are okay too).

**Comment by mark-buer** [comment]
In the problematic cases above, a common factor for the failures is that [`doFinal`](https://github.com/google/tink/blob/v1.2.2/java/src/main/java/com/google/crypto/tink/subtle/AesGcmHkdfStreaming.java#L246) is invoked with a zero length buffer.

Is it possible that Android 23 has a bug with this crypto provider where a zero length `doFinal` is somehow mishandled?

If so, an easy and safe fix would be to avoid that case by conditionalising the internals of [`AesGcmHkdfStreaming.encryptSegment(
        ByteBuffer part1, ByteBuffer part2, boolean isLastSegment, ByteBuffer ciphertext)`](https://github.com/google/tink/blob/v1.2.2/java/src/main/java/com/google/crypto/tink/subtle/AesGcmHkdfStreaming.java#L246) such that we either do `update` then `doFinal` or just a `doFinal` depending on whether `part2` is non-empty or empty respectively.

**Comment by mark-buer** [comment]
For anyone who stumbles into this issue before it is fixed, it is possible to workaround it by wrapping the output stream such that buffer writes of a problematic size are avoided:

```kotlin
import java.io.FilterOutputStream
import java.io.IOException
import java.io.OutputStream
import java.nio.ByteBuffer
import kotlin.math.min

class BufferSizeBugAvoidanceStreamWrapper(out: OutputStream) : FilterOutputStream(out) {

    private val _buffer: ByteBuffer = ByteBuffer.allocate(4080)
        .apply {
            limit(4041)
        }

    @Synchronized
    @Throws(IOException::class)
    override fun write(bytes: ByteArray, offset: Int, length: Int) {
        var inputOffset = offset
        var inputRemaining = length
        while (inputRemaining > 0) {
            val transfer = min(_buffer.remaining(), inputRemaining)
            _buffer.put(bytes, inputOffset, transfer)
            inputOffset += transfer
            inputRemaining -= transfer
            if (!_buffer.hasRemaining()) {
                _buffer.flip()
                out.write(_buffer.array(), _buffer.position(), _buffer.remaining())
                _buffer.limit(4080)
            }
        }
    }

    @Synchronized
    @Throws(IOException::class)
    override fun close() {
        _buffer.flip()
        if (_buffer.hasRemaining()) {
            out.write(_buffer.array(), _buffer.position(), _buffer.remaining())
        }
        super.close()
    }

}
```

**Comment by przydatek** [comment]
Hi Mark,
thanks a lot for this report and the thorough analysis!  We'll definitely into it soon, but given that you've already have an idea how to fix it, maybe you'd like to contribute a PR?
Cheers,

- Bartosz.

**Comment by freygriff** [comment]
Confirm

Freya Griffin

----- Reply message -----

**Comment by freygriff** [comment]
Confirm

Freya Griffin

----- Reply message -----
From: "ms.freyanabours97@gmail.com" <ms.freyanabours97@gmail.com>
To: "google/tink" <reply@reply.github.com>, "google/tink" <tink@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Subject: [google/tink] Android API 23 fails to round trip AES256_GCM_HKDF_4KB for particular buffer write combinations (#229)
Date: Wed, Jul 10, 2019 7:34 AM

Confirm

Freya Griffin

----- Reply message -----

**Comment by mark-buer** [comment]
I'm working on a PR now.
