### ISSUE TITLE
Failed to build with bazel

### ISSUE THREAD

**Issue by Muslava** [google/tink#266]
Greetings,
I try to build Tinkey following the instructions from the .md file but it returns me:

`C:\Users\coner\Desktop\tink>bazel build tools/tinkey/...
ERROR: C:/users/coner/_bazel_coner/2toaqi6b/external/com_google_protobuf_javalite/protobuf.bzl:127:19: Traceback (most recent call last):
        File "C:/users/coner/_bazel_coner/2toaqi6b/external/com_google_protobuf_javalite/protobuf.bzl", line 122
                rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
        File "C:/users/coner/_bazel_coner/2toaqi6b/external/com_google_protobuf_javalite/protobuf.bzl", line 127, in rule
                attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: C:/users/coner/desktop/tink/tools/tinkey/BUILD.bazel:7:1: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors and referenced by '//tools/tinkey:libtinkey'
ERROR: Analysis of target '//tools/tinkey:libtinkey' failed; build aborted: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 2.461s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 149 targets configured)
    currently loading: @remote_java_tools_windows//`

Also with the Tink Java example fails, it only worked with Maven.

**Comment by thaidn** [comment]
Which bazel version were you using?

If possible, can you try again with the latest Bazel?

**Comment by billylo1** [comment]
> Thanks! I was using the 0.29.1 version installed by Chocolatey, now I've upgrade it to 1.0.0 with the same program and builded the example in another folder.
> All done!

Hi, any chance you can share some details?  Trying to compile Tink C++ on Windows as well to produce a DLL consumerable by Windows app.  thx, Billy.
