### ISSUE TITLE
Class resolution issues on Android when a protobuf-java dependency

### ISSUE THREAD

**Issue by jdkizer9** [google/tink#282]
While I'm not sure this is specifically a Tink issue, I figured that I would post it here to see if anyone has come across it, and in the possible case that someone will come across this in the future.

In our application, everything behaves as expected during normal debug / production, but we're running into issues during testing, due to the fact that we're including the latest versions of `roboelectric` and `espresso-contrib`, both of which include protobuf-java as a transitive dependency. Note that we're using `com.google.crypto.tink:tink-android:1.3.0-rc1`.

The stack trace for the error is as follows:
```
java.lang.NoSuchMethodError: com.google.crypto.tink.proto.RegistryConfig.emptyProtobufList()Lcom/google/protobuf/Internal$ProtobufList;

	at com.google.crypto.tink.proto.RegistryConfig.<init>(RegistryConfig.java:22)
	at com.google.crypto.tink.proto.RegistryConfig.<clinit>(RegistryConfig.java:541)
	at com.google.crypto.tink.config.TinkConfig.<clinit>(TinkConfig.java:42)
	at org.thecommonsproject.android.tinktest.TinkTest.configureTink(TinkTest.kt:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I did some digging into the stack trace, and it looks like `RegistryConfig` is inheriting from the `protobuf-java` version of `GeneratedMessageLite` rather than the `protobuf-lite` version. Somewhat surprisingly, this issue did not appear until I upgraded to Android Studio 3.5.

The dependency graph is:

```
com.google.protobuf:protobuf-java:2.6.1
\--- com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
    +--- androidx.test.espresso:espresso-contrib:3.2.0-beta01 (requested com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.0)
    |    \--- customConfig
    \--- org.robolectric:shadows-framework:4.3-beta-1
         \--- org.robolectric:robolectric:4.3-beta-1
              \--- customConfig
```
As you can see, it looks like `accessibility-test-framework` is the source of the `protobuf-java` dependency.

I was able to resolve this by excluding 'protobuf-java' from all configurations, adding the following to my module's `.gradle` file:
```
configurations {
    all*.exclude module: 'protobuf-java'
}
```
I doubt this is the best solution, but it seems to be working for now.

I put together a [sample project](https://github.com/jdkizer9/TinkTestDependencyIssue) that demonstrates this. As I mentioned above, I didn't see this issue until I upgraded to Android Studio 3.5, so it may work as expected in previous versions of Android Studio. 

Any feedback would be greatly appreciated.

**Comment by thaidn** [comment]
Hi there,

What you did is correct, thanks for documenting a workaround and providing a working example!

Could you please send a PR to update the JAVA-HOWTO with your workaround and include a pointer to your sample project?

Related issues: https://github.com/google/tink/issues/253 and https://github.com/google/tink/issues/257.

**Comment by thaidn** [comment]
@jdkizer9 could you please try 1.3.0-RC3? It should work without your workaround.

**Comment by thaidn** [comment]
Please reopen if you have any other issues.
