### ISSUE TITLE
ExceptionInInitializerError on the last version 1.3.0 for Android

### ISSUE THREAD

**Issue by Pschsch** [google/tink#323]
While trying to register Tink, app crashes at `KeysetHandle.generateNew(AeadKeyTemplates.AES256_GCM)` Same result in another key templates.

**Comment by thaidn** [comment]
Could you please provide the full stack trace? There's a known issue with protobuf. If you also depend on for example Firebase, there's a protobuf dependency conflict.

**Comment by simtse** [comment]
@thaidn So we're running into an exception in initializing that came up in 1.3.0 in our CI that uses Firebase Test Lab. Generally, it passed, but we have another 

```
E/TinkSecurity(19146): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.protobuf.Writer$FieldOrder com.google.protobuf.Writer.fieldOrder()' on a null object reference
E/TinkSecurity(19146): 	at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2529)
E/TinkSecurity(19146): 	at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:268)
E/TinkSecurity(19146): 	at com.google.crypto.tink.KeyManagerImpl.newKeyData(KeyManagerImpl.java:121)
E/TinkSecurity(19146): 	at com.google.crypto.tink.Registry.newKeyData(Registry.java:716)
E/TinkSecurity(19146): 	at com.google.crypto.tink.KeysetManager.newKey(KeysetManager.java:231)
E/TinkSecurity(19146): 	at com.google.crypto.tink.KeysetManager.addNewKey(KeysetManager.java:91)
E/TinkSecurity(19146): 	at com.google.crypto.tink.KeysetManager.rotate(KeysetManager.java:68)
E/TinkSecurity(19146): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager.readOrGenerateNewKeyset(AndroidKeysetManager.java:306)
E/TinkSecurity(19146): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager.<init>(AndroidKeysetManager.java:124)
E/TinkSecurity(19146): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager.<init>(AndroidKeysetManager.java:88)
E/TinkSecurity(19146): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:185)
E/TinkSecurity(19146): 	at com.sample.TinkCrypto.initTink(TinkCrypto.kt:124)
```

**Comment by thaidn** [comment]
This is a known issue. We're working on a fix. It should be available in HEAD-SNAPSHOT next week and included in 1.4.0-RC2.

**Comment by thaidn** [comment]
This is fixed in HEAD-SNAPSHOT. Please try it out to see if it helps, instructions are at https://github.com/google/tink/issues/357#issuecomment-626088722.

**Comment by thaidn** [comment]
This is a dup of #301. Let's move the discussion over there.
