### ISSUE TITLE
Build Issue build_bazel_apple_support): The system cannot find the file specified.

### ISSUE THREAD

**Issue by Nrsh1986** [google/tink#352]
Hi,
I had a build issue on my windows system after installing bazel Via chocolaty am initiating the build but am getting the below error. Help me what am doing wrong.

D:\tink\tools>bazel build tinkey
INFO: Call stack for the definition of repository 'build_bazel_apple_support' which is a git_repository (rule definition at C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - <builtin>
 - C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/tink_cc/tink_cc_deps.bzl:77:9
 - D:/tink/tools/WORKSPACE:30:1
ERROR: An error occurred during the fetch of repository 'build_bazel_apple_support':
   Traceback (most recent call last):
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
                init(ctx, git_repo)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(<1 more arguments>)
error running 'git init C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/build_bazel_apple_support' while working with @build_bazel_apple_support:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/build_bazel_apple_support): The system cannot find the file specified.
 (error: 2)
ERROR: no such package '@build_bazel_apple_support//lib': Traceback (most recent call last):
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
                _clone_or_update(ctx)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
                git_repo(ctx, directory)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
                _update(ctx, git_repo)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
                init(ctx, git_repo)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
                _error(ctx.name, cl, st.stderr)
        File "C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
                fail(<1 more arguments>)
error running 'git init C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/build_bazel_apple_support' while working with @build_bazel_apple_support:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/naresh.p/_bazel_naresh.p/ooboooxf/external/build_bazel_apple_support): The system cannot find the file specified.

**Comment by tholenst** [comment]
I'm sorry, but we currently do not support C++ on windows.

**Comment by thaidn** [comment]
Closing this to clean up the queue.
