### ISSUE TITLE
Conflict with Gauva 29.0-android

### ISSUE THREAD

**Issue by ZacSweers** [google/tink#356]
When we try to update to Guava 29.0-android, we see this trace (originating from the androidx crypto library)

```
java.lang.UnsupportedOperationException
at com.google.protobuf.AbstractProtobufList.ensureIsMutable(AbstractProtobufList.java:172)
at com.google.protobuf.ProtobufArrayList.add(ProtobufArrayList.java:78)
at com.google.crypto.tink.proto.Keyset.addKey(Keyset.java:868)
at com.google.crypto.tink.proto.Keyset.access$1700(Keyset.java:16)
at com.google.crypto.tink.proto.Keyset$Builder.addKey(Keyset.java:1142)
at com.google.crypto.tink.KeysetManager.addNewKey(KeysetManager.java:92)
at com.google.crypto.tink.KeysetManager.rotate(KeysetManager.java:68)
at com.google.crypto.tink.integration.android.AndroidKeysetManager.readOrGenerateNewKeyset(AndroidKeysetManager.java:306)
at com.google.crypto.tink.integration.android.AndroidKeysetManager.<init>(AndroidKeysetManager.java:124)
at com.google.crypto.tink.integration.android.AndroidKeysetManager.<init>(AndroidKeysetManager.java:88)
at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:185)
at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:121)
```

**Comment by thaidn** [comment]
This is a known issue. We're working on a fix. It should be available in HEAD-SNAPSHOT next week and included in 1.4.0-RC2.

**Comment by thaidn** [comment]
This is fixed in HEAD-SNAPSHOT. Please try it out to see if it helps, instructions are at https://github.com/google/tink/issues/357#issuecomment-626088722.

**Comment by thaidn** [comment]
This is a dup of #301. Let's move the discussion over there.

**Comment by ZacSweers** [comment]
Confirmed the snapshot resolves this for us, looking forward to the next release 👍

**Comment by thaidn** [comment]
Awesome! 1.4.0-RC2 is coming next week.
