### ISSUE TITLE
ImportError: cannot import name 'hybrid' from 'tink' (unknown location)

### ISSUE THREAD

**Issue by hpnhxxwn** [google/tink#369]
Hi, I used PyPi to install Tink from test.pypi.org. And then I used Python 3 to try out Python code sample in the repo. Below is the issue I got:
```
>>> import tink
>>> from tink import hybrid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'hybrid' from 'tink' (unknown location)
>>> from tink import signature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'signature' from 'tink' (unknown location)
>>> from tink import aead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'aead' from 'tink' (unknown location)
```

Could did I miss? Thank you!

**Comment by kste** [comment]
Which OS and Python version is this on?

**Comment by hpnhxxwn** [comment]
@kste I have reinstalled python 3.7 on MacOS, uninstalled Tink, rebuild and reinstalled Tink. Now I have this error:
```
Python 3.7.5 (default, Oct 22 2019, 10:35:10)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/znifly/tink/python/tink/__init__.py", line 21, in <module>
    from tink import _keyset_handle
  File "/Users/znifly/tink/python/tink/_keyset_handle.py", line 25, in <module>
    from google.protobuf import message
ModuleNotFoundError: No module named 'google'
```

I do have protoc installed on my Mac.
```
protoc --version
libprotoc 3.12.3
```

**Comment by kste** [comment]
Did pip install the protobuf package (`pip3 freeze`)? This should have happened automatically when running `pip3 install .` in the Tink folder, as it's part of the `requirements.txt`.

**Comment by hpnhxxwn** [comment]
@kste Yes :) Here is output of pip3 freeze and I have protobuf installed. 
```
pip3 freeze
absl-py==0.2.1
protobuf==3.12.2
six==1.10.0
tink==1.4.0rc2
```

**Comment by hpnhxxwn** [comment]
I managed to make it work with a virtual env, rebuild with bazel and install with pip3.
