### ISSUE TITLE
Bazel + Pip install failed

### ISSUE THREAD

**Issue by hpnhxxwn** [google/tink#370]
Hi, I am building Tink on my Mac locally. I installed Tink using the Python HOWTO guideline. Then I opened Python3.6 and import Tink, I got the following errors: 

```
>>> import tink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/__init__.py", line 21, in <module>
    from tink import _keyset_handle
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/_keyset_handle.py", line 27, in <module>
    from tink import _keyset_reader
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/_keyset_reader.py", line 29, in <module>
    from tink import core
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/core/__init__.py", line 22, in <module>
    from tink.core import _crypto_format
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/core/_crypto_format.py", line 25, in <module>
    from tink.core import _tink_error
  File "/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/core/_tink_error.py", line 21, in <module>
    from tink.cc.pybind import tink_bindings
ImportError: dlopen(/Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/cc/pybind/tink_bindings.cpython-36m-darwin.so, 2): Symbol not found: _PyThread_tss_alloc
  Referenced from: /Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/cc/pybind/tink_bindings.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/znifly/Library/Python/3.6/lib/python/site-packages/tink/cc/pybind/tink_bindings.cpython-36m-darwin.so
```

**Comment by kste** [comment]
Python3.6 is not supported (some of the type hints are not supported in <=3.6), but this still seems to be caused by a different issue.

Was the package build successfully with Python3.6?

**Comment by hpnhxxwn** [comment]
> Python3.6 is not supported (some of the type hints are not supported in <=3.6), but this still seems to be caused by a different issue.
> 
> Was the package build successfully with Python3.6?

I followed the instruction, did "bazel build ..." and it was successful. "bazel test" was also successful.

**Comment by leighmcculloch** [comment]
I experienced a similar issue but switched to Python 3.7 and it worked.

**Comment by hpnhxxwn** [comment]
Hi @leighmcculloch, wondering if you had this problem on Mac? I have rebuild and installed using python 3.7.
```
Python 3.7.5 (default, Oct 22 2019, 10:35:10)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tink import aead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'aead' from 'tink' (unknown location)
>>>
```

**Comment by hpnhxxwn** [comment]
I managed to make it work by creating a virtual env, and rebuild with bazel + pip3 in the env.
