### ISSUE TITLE
GCPKmsClient with existing Credentials

### ISSUE THREAD

**Issue by satishkumarganesan** [google/tink#418]
Hello Team

GcpKmsClient() doesn't seem to expose withCredentials which can accept an existing Credentials (PR pull 244 suggests this is fixed)

We are trying to use tink with authenticated proxy. We are hoping to use this function getApplicationDefault(HttpTransportFactory transportFactory) which customizes the proxy as per this article https://github.com/googleapis/google-auth-library-java/blob/master/README.md#configuring-a-proxy

It would be great if you could guide me on this.

Thanks

Satish

**Comment by thaidn** [comment]
How's about this https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L111?

**Comment by thaidn** [comment]
Please ping back if you still want to chat about this.

**Comment by etnichols** [comment]
I have a similar question -- I am also trying to run tink within a Spring Boot server locally. I have a service account JSON downloaded locally (into `src/main/j/c/main/resources/my_dev_creds.json`). I'm trying to initialize a GcpKmsClient using those credentials explicitly, but am limited by the fact that `register` only accepts a _path_ to credentials, not an actual GoogleCredential object.

Example:

```java
    public KeysetHandle generateKeyset() throws Exception {
        // Register all AEAD key types with the Tink runtime.
        AeadConfig.register();
        
        ClassPathResource credsResource = new ClassPathResource("my_cred_in_resources_folder.json");
        System.out.println("GCP creds filepath exists: " + credsResource.exists());
        
        InputStream credsAsStream = credsResource.getInputStream();
        
        // Explicitly create credentials from stream, this works.
        GoogleCredential credential = GoogleCredential.fromStream(credsAsStream);        
        GcpKmsClient kmsClient = new GcpKmsClient(kekUri).withCredentials(credential);

       // Trying to use this fails...
```

This creates the GcpKmsClient, but later attempts to use the client fail with the following error:

```
Handle creation failure: java.security.GeneralSecurityException: No KMS client does support: gcp-kms://[redacted]
java.security.GeneralSecurityException: No KMS client does support: gcp-kms://[redacted]
	at com.google.crypto.tink.KmsClients.get(KmsClients.java:60)
	at com.google.crypto.tink.aead.KmsAeadKeyManager$1.getPrimitive(KmsAeadKeyManager.java:46)
	at com.google.crypto.tink.aead.KmsAeadKeyManager$1.getPrimitive(KmsAeadKeyManager.java:42)
	at com.google.crypto.tink.KeyTypeManager.getPrimitive(KeyTypeManager.java:152)
	at com.google.crypto.tink.KeyManagerImpl.validateKeyAndGetPrimitive(KeyManagerImpl.java:138)
	at com.google.crypto.tink.KeyManagerImpl.getPrimitive(KeyManagerImpl.java:65)
	at com.google.crypto.tink.Registry.getPrimitiveInternal(Registry.java:978)
	at com.google.crypto.tink.Registry.getPrimitive(Registry.java:971)
	at com.google.crypto.tink.Registry.getPrimitive(Registry.java:1034)
	at com.google.crypto.tink.KeysetHandle.getPrimitiveWithKnownInputPrimitive(KeysetHandle.java:324)
	at com.google.crypto.tink.KeysetHandle.getPrimitive(KeysetHandle.java:345)
	at com.logchain.digitalsignature.util.Crypter.generateKeyset(Crypter.java:81)
```

Which, I expect, as the exposed `register` method Adds the given client to `KmsClients` here: https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L169.

Any advice? I feel like I'm making this more complicated than it needs to be :D

**Comment by etnichols** [comment]
Ah, I can simply add the client myself using the static `KmsClients.add` method. Resolved.
