### ISSUE TITLE
Unavoidable logcat warning

### ISSUE THREAD

**Issue by ansman** [google/tink#436]
When building `AndroidKeysetManager` the first time I see a warning like this:
```plain
AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value <name> does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
```

As far as I can see this warning should not be logged since it will always happen the first time and there is no way to fix around it.

**Comment by thaidn** [comment]
This is useful because it allows us to know when Tink decided to generate a brand new keyset.

Why is a warning a problem?

**Comment by ansman** [comment]
It's annoying to see a big yellow chunk of warning on startup. We keep our logcat lean to be able to quickly detect issues.

This should probably be hidden behind a debug flag. Or you can use logcat properties to decide if the log tag should be used.

This is especially bad for production since apps should ideally not print to logcat in production because it's noisy as it is.

**Comment by occultus73** [comment]
@thaidn by all means, keep it as a verbose log message, it's just warning look bad in release builds on the logcat. My lead asked me to see if there was anyway of getting rid of it today - I linked him this thread.

**Comment by thaidn** [comment]
Got ya. I'm fixing this.

**Comment by Gigyasha** [comment]
When creating the encrypted shared preferences I got this exception for the first time when file gets created, I saw in the GitHub code that log.w() is written with the exception object, this big chunk of code doesn't not look good , its better to keep only log message without the exception object

 9638-9638/com.example.ssp W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
