### ISSUE TITLE
Error: cannot verify signature while decrypting a Google Pay Token 

### ISSUE THREAD

**Issue by pchaudhary0909** [google/tink#512]
I'm using below Java code from Tink library to decrypt a Google Token:

String decryptedMessage =
                new PaymentMethodTokenRecipient.Builder()
                        .fetchSenderVerifyingKeysWith(
                                GooglePaymentsPublicKeysManager.INSTANCE_TEST)
                        .recipientId( "01234567890123456789") // "12345678901234567890"))
                        .protocolVersion("ECv2")
                        .addRecipientPrivateKey("<newPrivateKey>")
                        .addRecipientPrivateKey("<oldPrivateKey>")
                        .build()
                        .unseal("<paymentMethodToken>");

- Instance used is TEST
- RECEIPENT ID: tested with both 01234567890123456789 and 12345678901234567890

I've not updated the public key in the Google console account as my understanding is that since we are using the test merchant ID 01234567890123456789, it might not be needed.

The exception message that I'm getting is:
[05-26-21 16:20:25.618] [http-nio-8080-exec-10] ERROR  c.p.p.c.DecryptTokenController - Caught Exception while Decrypting & Tokenizing the PaymentMethodToken. Stack:java.security.GeneralSecurityException: **cannot verify signature**
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verify(PaymentMethodTokenRecipient.java:458)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verifyECV2(PaymentMethodTokenRecipient.java:398)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unsealECV2(PaymentMethodTokenRecipient.java:363)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unseal(PaymentMethodTokenRecipient.java:340)

Could you please look into it.

**Comment by yozenou** [comment]
@pchaudhary0909 Hey how are you ?
Do you find any solution to decrypt the token ? i have the same error Cause: java.security.GeneralSecurityException: **cannot verify signature** .

Thanks for your help !
