### ISSUE TITLE
Decryption Failed due to General Security Exception but also Tag Mismatch is occurring sometimes.

### ISSUE THREAD

**Issue by electrodragon** [google/tink#522]
I'm encrypting and decrypting a string in the same function. But I'm getting an error of `GeneralSecurityException` for decrypting. if the cipherText in the form of byte array is provided as it is to the decrypting function it works fine. but if I create a string from that cipherText byte array, and provide that string as bytes array to decrypted function it fails.

Tag Mismatch error also occurs rarely if the program is run for few times (5 to 10) times.

If Tink works with byte array only, as I want to encrypt a string, and the encrypted form is the byte array, do I have to save that byte array in the database because the byte array reconverted to string isn't working. The same also applies to TAG. do I have to
save the bytes generated of TAG for decryption purpose?

Here is my function.
```
public static void test() throws GeneralSecurityException {
    AeadConfig.register(); // Registering only Aead Primitive
    
    Aead aead = KeysetHandle.generateNew(KeyTemplates.get("AES256_GCM"))
            .getPrimitive(Aead.class);

    String secretKey = "TinkIsCrazy";

    byte[] cipherText = aead.encrypt("Hello, World!".getBytes(), secretKey.getBytes());
    String encryptedText = new String(cipherText);

    // Decrypting cipherText Works Fine
    byte[] decrypted = aead.decrypt(cipherText, secretKey.getBytes());
    System.out.println(new String(decrypted));

    // Decrypting encryptedText doesn't Work
    decrypted = aead.decrypt(encryptedText.getBytes(), secretKey.getBytes());
    System.out.println(new String(decrypted));
}
```

**Output 1:**
This one with Tag mismatch error.
```
/usr/lib/jvm/java-15-openjdk/bin/java -javaagent:/opt/idea-IC-211.6693.111/lib/idea_rt.jar=35269:/opt/idea-IC-211.6693.111/bin -Dfile.encoding=UTF-8 -classpath /home/attaullah/IdeaProjects/TinkTesting/target/classes:/home/attaullah/.m2/repository/com/google/crypto/tink/tink/1.6.0/tink-1.6.0.jar:/home/attaullah/.m2/repository/com/google/protobuf/protobuf-java/3.14.0/protobuf-java-3.14.0.jar:/home/attaullah/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar TutaNota
Hello, World!
Jun 22, 2021 3:34:24 AM com.google.crypto.tink.aead.AeadWrapper$WrappedAead decrypt
INFO: ciphertext prefix matches a key, but cannot decrypt: javax.crypto.AEADBadTagException: Tag mismatch!
Exception in thread "main" java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
	at TutaNota.test(TutaNota.java:73)
	at TutaNota.main(TutaNota.java:14)

Process finished with exit code 1

```

**Output 2:**
This one without Tag mismatch error.
```
/usr/lib/jvm/java-15-openjdk/bin/java -javaagent:/opt/idea-IC-211.6693.111/lib/idea_rt.jar=36885:/opt/idea-IC-211.6693.111/bin -Dfile.encoding=UTF-8 -classpath /home/attaullah/IdeaProjects/TinkTesting/target/classes:/home/attaullah/.m2/repository/com/google/crypto/tink/tink/1.6.0/tink-1.6.0.jar:/home/attaullah/.m2/repository/com/google/protobuf/protobuf-java/3.14.0/protobuf-java-3.14.0.jar:/home/attaullah/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar TutaNota
Hello, World!
Exception in thread "main" java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
	at TutaNota.test(TutaNota.java:73)
	at TutaNota.main(TutaNota.java:14)

Process finished with exit code 1
```

**Comment by thaidn** [comment]
Tink is not crazy ;-)

The problem is in this line:

```
String encryptedText = new String(cipherText);
```

Quoting https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#String(byte[]):

```
Constructs a new String by decoding the specified array of bytes using the platform's default charset. The length of the new String is a function of the charset, and hence may not be equal to the length of the byte array.

The behavior of this constructor when the given bytes are not valid in the default charset is unspecified. The CharsetDecoder class should be used when more control over the decoding process is required.
```

Two potential solutions:

1/ Base64 encoding:

```
import java.util.Base64;

String encrypted  = Base64.getEncoder().encodeToString(ciphertext);

```

2/ UTF_8 encoding:

```
import static java.nio.charset.StandardCharsets.UTF_8;

String encrypted  = new String(ciphertext, UTF_8);

```

**Comment by electrodragon** [comment]
@thaidn So now Java is crazy :)
tried both solutions Base64, and StandardCharsets.UTF_8 solution, but still GeneralSecurityException :(

**Comment by thaidn** [comment]
Can you share new snippets that use Base64 or UTF_8?

**Comment by electrodragon** [comment]
Base 64 Snippet:
```
import com.google.crypto.tink.*;
import com.google.crypto.tink.aead.AeadConfig;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.util.Base64;

public class EncDec {
    public static void main(String[] args) throws GeneralSecurityException {
        AeadConfig.register(); // Registering only Aead Primitive

        Aead aead = KeysetHandle.generateNew(KeyTemplates.get("AES256_GCM"))
                .getPrimitive(Aead.class);

        String secretKey = "TinkIsNotCrazy;-)";

        byte[] cipherText = aead.encrypt("Hello, World!".getBytes(StandardCharsets.UTF_8), secretKey.getBytes());
        String encryptedText  = Base64.getEncoder().encodeToString(cipherText);

        // Decrypting cipherText Works Fine
        byte[] decrypted = aead.decrypt(cipherText, secretKey.getBytes());
        System.out.println(new String(decrypted));

        // Decrypting encryptedText doesn't Work
        decrypted = aead.decrypt(encryptedText.getBytes(), secretKey.getBytes());
        System.out.println(new String(decrypted));
    }
}
```
**Output:** 
```
/usr/lib/jvm/java-15-openjdk/bin/java -javaagent:/opt/idea-IC-211.6693.111/lib/idea_rt.jar=33627:/opt/idea-IC-211.6693.111/bin -Dfile.encoding=UTF-8 -classpath /home/attaullah/IdeaProjects/TinkTesting/target/classes:/home/attaullah/.m2/repository/com/google/crypto/tink/tink/1.6.0/tink-1.6.0.jar:/home/attaullah/.m2/repository/com/google/protobuf/protobuf-java/3.14.0/protobuf-java-3.14.0.jar:/home/attaullah/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar EncDec
Hello, World!
Exception in thread "main" java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
	at EncDec.main(EncDec.java:24)

Process finished with exit code 1
```

UTF_8 Snippet:
```
import com.google.crypto.tink.*;
import com.google.crypto.tink.aead.AeadConfig;
import java.security.GeneralSecurityException;
import static java.nio.charset.StandardCharsets.UTF_8;

public class EncDec {
    public static void main(String[] args) throws GeneralSecurityException {
        AeadConfig.register(); // Registering only Aead Primitive

        Aead aead = KeysetHandle.generateNew(KeyTemplates.get("AES256_GCM"))
                .getPrimitive(Aead.class);

        String secretKey = "TinkIsNotCrazy;-)";

        byte[] cipherText = aead.encrypt("Hello, World!".getBytes(UTF_8), secretKey.getBytes());
        String encryptedText  = new String(cipherText, UTF_8);

        // Decrypting cipherText Works Fine
        byte[] decrypted = aead.decrypt(cipherText, secretKey.getBytes());
        System.out.println(new String(decrypted));

        // Decrypting encryptedText doesn't Work
        decrypted = aead.decrypt(encryptedText.getBytes(), secretKey.getBytes());
        System.out.println(new String(decrypted));
    }
}
```
**Output:** 
```
/usr/lib/jvm/java-15-openjdk/bin/java -javaagent:/opt/idea-IC-211.6693.111/lib/idea_rt.jar=40175:/opt/idea-IC-211.6693.111/bin -Dfile.encoding=UTF-8 -classpath /home/attaullah/IdeaProjects/TinkTesting/target/classes:/home/attaullah/.m2/repository/com/google/crypto/tink/tink/1.6.0/tink-1.6.0.jar:/home/attaullah/.m2/repository/com/google/protobuf/protobuf-java/3.14.0/protobuf-java-3.14.0.jar:/home/attaullah/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar EncDec
Hello, World!
Exception in thread "main" java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
	at EncDec.main(EncDec.java:24)

Process finished with exit code 1
```

**Comment by thaidn** [comment]
You forgot to Base64 decode `encrypted` back to a byte array before passing
it to decrypt().

**Comment by electrodragon** [comment]
Yay! Thanks a lot, now working!

**Comment by stevezuju** [comment]
@chuckx 
I have read the conversation above. Encrypt base 64 is work, but UTF-8 it not, can you let me know the reason why ? 
Thanks
