### ISSUE TITLE
Broken tink 1.6.1 macOS wheel

### ISSUE THREAD

**Issue by rbange** [google/tink#539]
**Help us help you**

Please tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/edit).

**Describe the bug**

Tink cannot be imported.

**To Reproduce**

`python -m venv .venv`
`source .venv/bin/activate`
`pip install tink==1.6.1`
`python -c "import tink"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./.venv/lib/python3.9/site-packages/tink/__init__.py", line 20, in <module>
    from tink import _keyset_handle
  File "./.venv/lib/python3.9/site-packages/tink/_keyset_handle.py", line 27, in <module>
    from tink import _keyset_reader
  File "./.venv/lib/python3.9/site-packages/tink/_keyset_reader.py", line 30, in <module>
    from tink import core
  File "./.venv/lib/python3.9/site-packages/tink/core/__init__.py", line 22, in <module>
    from tink.core import _crypto_format
  File "./.venv/lib/python3.9/site-packages/tink/core/_crypto_format.py", line 25, in <module>
    from tink.core import _tink_error
  File "./.venv/lib/python3.9/site-packages/tink/core/_tink_error.py", line 21, in <module>
    from tink.cc.pybind import tink_bindings
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.9.4 (default, Apr  7 2021, 09:32:34)
[Clang 12.0.0 (clang-1200.0.32.29)].
```

**Expected behavior**

`python -m venv .venv`
`source .venv/bin/activate`
`pip install tink==1.6.0`
`python -c "import tink"` -> works

**Error messages, stack traces, etc.**

If applicable, please include error messages, stack traces or any debugging
information.

**Version information**

 - Language: Python 
 - Version: 3.9.4
 - Environment: MacOS 11.5.1, pip 21.0.1

**Additional context**

Add any other context about the problem.

**Comment by thaidn** [comment]
Thanks. I'm investigating.

**Comment by thaidn** [comment]
In the meantime, can you use tink 1.6.0? It should work.

**Comment by rbange** [comment]
Yes sure, 1.6.0 works fine for me

**Comment by thaidn** [comment]
Can you try again?

```
pip3.9 --no-cache-dir install tink
```

This should work.

**Comment by rbange** [comment]
Yes, works now. 
Thank you 🎉
