### ISSUE TITLE
Java Tink depends on Android annotation while not depending on it

### ISSUE THREAD

**Issue by bountin** [google/tink#622]
Our dependabot update from 1.6.1 to 1.7.0 failed with the following error:
```
/home/bountin/.gradle/caches/modules-2/files-2.1/com.google.crypto.tink/tink/1.7.0/668b57f109d32349b2870448f06ae6f202713edc/tink-1.7.0.jar(/com/google/crypto/tink/JsonKeysetReader.class): warning: Cannot find annotation method 'value()' in type 'RequiresApi': class file for androidx.annotation.RequiresApi not found
error: warnings found and -Werror specified
1 error
1 warning
```

Apparently, the POM is missing the dependency but it wasn't there in 1.6.1 either. So probably it's the first time that the java (not android!) variant is using `@RequiresApi`. Unfortunately, there is no PR for the change but only (duplicate) commits that make it really hard for me to track what has changes.

## Environment

-   Language: Java
-   Version: 1.7.0
-   Environment: Gradle 7.5.1

**Comment by AndreasALoew** [comment]
same issue here: project uses NO Android at all, just trying to update Tink to 1.7.0 and warnings everywhere:

`[WARNING] Cannot find annotation method 'value()' in type 'androidx.annotation.RequiresApi': class file for androidx.annotation.RequiresApi not found
`

:-( Please fix this asap! thx! :-)

**Comment by tholenst** [comment]
Sorry for missing this earlier, I will take a look.

**Comment by morambro** [comment]
Hi, we've updated the POM file, could you please test upgrading to `HEAD-SNAPSHOT` and let us know if this works?
```
<dependency>
  <groupId>com.google.crypto.tink</groupId>
  <artifactId>tink</artifactId>
  <version>HEAD-SNAPSHOT</version>
</dependency>
```

**Comment by AndreasALoew** [comment]
Sorry, this might be a dumb question, but as I am just an ordinary Java developer and unfamiliar with bazel builds, can you please advise **how I can install the HEAD-SNAPSHOT version of tink into my local Maven repo** (~/.m2/repository) after cloning the tink master branch?

**Comment by morambro** [comment]
> dreasALoew

This should work:
```
git clone https://github.com/google/tink.git
cd tink/java_src
../maven/maven_deploy_library.sh install tink ../maven/tink.pom.xml HEAD
```

**Comment by AndreasALoew** [comment]
Sorry again, but still not there yet...
Trying to use bazelisk, as it seems that tink is tied to an older version 5.1.1 of bazel - but now getting the following (on RHEL8), so please advise again:

```
[andreasaloew@MDXN00105831:/mnt/d/GitHub/tink/java_src]$ ../maven/maven_deploy_library.sh install tink ../maven/tink.pom.xml HEAD
+ bazel build tink.jar tink-src.jar tink-javadoc.jar
Starting local Bazel server and connecting to it...
DEBUG: /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 5.1.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
ERROR: /mnt/d/GitHub/tink/java_src/BUILD.bazel:15:20: every rule of type javadoc_library implicitly depends upon the target '@androidsdk//:platforms/android-23/android.jar', but this target could not be found because of: no such target '@androidsdk//:platforms/android-23/android.jar': target 'platforms/android-23/android.jar' not declared in package '' defined by /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/androidsdk/BUILD.bazel
ERROR: Analysis of target '//:tink-javadoc.jar' failed; build aborted:
INFO: Elapsed time: 13.709s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (31 packages loaded, 5 targets configured)
*** Failed executing command. ***
Failed command: bazel build tink.jar tink-src.jar tink-javadoc.jar
```
Sorry - but bazel seems to be just another universe of its own... ❓

**Comment by AndreasALoew** [comment]
OK, so I simply added the Sonatype Snaphots repo - much easier indeed... 😃 ❗ 

**Good news**: Yes, I think I can confirm that the dependency to "androidx.annotation.RequiresApi" is now gone again - no warnings any more on our build with version HEAD-SNAPSHOT... 👍 

Final remark wrt building tink-java (non-Android) from scratch: Is it indeed your intention that one needs to install a full Android SDK in order to compile a plain-Java-non-Android version of tink that **must not** have any reference to the Android ecosystem?

I think it is indeed this (IMHO) **very unfortunate setup** that has originally caused this type of error to be introduced into the plain-Java-non-Android version of Tink:

As even the build process for non-Android requires Android SDK to be in place, you will never have a chance to detect that you might have mistakenly introduced dependencies to Android. Just my 50 Euro cents of course... 😞 

Please release an official tink version soon with this fix so that we can update to an official 1.7.x from 1.6.1.
Many thanks! 😃

**Comment by tholenst** [comment]
Building the java version should *not* require the android toolchain. My assumption was only that it requires these annotation classes, which are very lightweight and have basically no impact.

It would be possible to remove these from the java build, but I simply see no reason for that at the moment, as they are so lightweight. 

Is my understanding wrong?

**Comment by morambro** [comment]
Tink Java doesn't depend on Android, only `javadoc_library` depends upon the target `@androidsdk//:platforms/android-23/android.jar` (see error message in [the comment above](https://github.com/google/tink/issues/622#issuecomment-1280791943)). Indeed the annotations are independent from Android.

**Comment by AndreasALoew** [comment]
Then maybe the howto docs that @morambro provided as a link are wrong, too:
https://github.com/google/tink/blob/master/docs/JAVA-HACKING.md#hacking-tink-for-java-and-android
states:
_To build Java, install Android SDK 23 or newer and set the ANDROID_HOME environment variable to the path of your Android SDK. On macOS, the SDK is usually installed at /Users/username/Library/Android/sdk/. You also need Android SDK Build Tools 24.0.3 or newer._

**Comment by AndreasALoew** [comment]
Looks like it is even worse, but this is probably tied to bazel: Even if I change "maven_deploy_library.sh" to only build target "//:tink.jar", I still get errors about not having installed a **C compiler** 😞 

```
[andreasaloew@MDXN00105831:/mnt/d/GitHub/tink/java_src]$ ../maven/maven_deploy_library.sh install tink ../maven/tink.pom.xml HEAD
+ bazel build tink.jar
Starting local Bazel server and connecting to it...
DEBUG: /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 5.1.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
INFO: Repository local_config_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:519:13: in <toplevel>
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/cc_configure.bzl:184:16: in cc_configure
Repository rule cc_autoconf defined at:
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/cc_configure.bzl:145:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:519:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/cc_configure.bzl", line 127, column 33, in cc_autoconf_impl
                configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 345, column 17, in configure_unix_toolchain
                cc = find_cc(repository_ctx, overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 23, in find_cc
                cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 306, column 32, in _find_generic
                auto_configure_fail(msg)
        File "/home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:392:6: in <toplevel>
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository maven instantiated at:
  /mnt/d/GitHub/tink/java_src/WORKSPACE:17:14: in <toplevel>
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/rules_jvm_external/defs.bzl:121:19: in maven_install
Repository rule coursier_fetch defined at:
  /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/rules_jvm_external/coursier.bzl:1173:33: in <toplevel>
ERROR: /home/andreasaloew/.cache/bazel/_bazel_andreasaloew/30aa4522c006c04bdbc7e8a960541239/external/bazel_tools/tools/jdk/BUILD:422:10: @bazel_tools//tools/jdk:proguard_whitelister depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
ERROR: Analysis of target '//:tink.jar' failed; build aborted:
INFO: Elapsed time: 10.015s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (65 packages loaded, 437 targets configured)
    Fetching https://mirror.bazel.build/bazel_java_tools/releases/java/v11.6/java_tools-v11.6.zip; 5s
    Fetching https://github.com/coursier/coursier/releases/download/v2.0.16/coursier.jar
*** Failed executing command. ***
Failed command: bazel build tink.jar
```

**Comment by bountin** [comment]
On the original issue: Yes, i was able to produce a working build now but I also needed to add the Google Maven Repository to the gradle build as `androidx.annotation:annotation:1.5.0` is not available on Maven Central. I don't know though if this is just a gradle thing and maven adds repositories recursively from dependencies or not.

**Comment by AndreasALoew** [comment]
Hmm - in order to access version HEAD-SNAPSHOT I had to temporarily open up an Internet-facing proxy for my build - and you are right, my build completed without errors, but also has downloaded
```
<!-- https://mvnrepository.com/artifact/androidx.annotation/annotation -->
<dependency>
    <groupId>androidx.annotation</groupId>
    <artifactId>annotation</artifactId>
    <version>1.5.0</version>
</dependency>
```
as an additional dependency (and seemingly from the Google repository (https://maven.google.com/) even though this has not been declared in our POMs at all...!?).

I don't really have an issue with that, but in case your plan was to get completely rid of this whole dependency (and not just the compile-time warnings), then I agree with @bountin that this attempt has still failed... 😞

**Comment by tholenst** [comment]
The plan was never to get rid of the dependency. The dependency shouldn't cause any harm (since it's just an annotation which the compiler should ignore on non-android Java). If there is a problem with the annotation let me know, otherwise as far as I know this is fixed.

**Comment by bountin** [comment]
@tholenst The dependency only creates harm in a sense that Google Tink is available on Maven Central but the annotation dependency is not. Users thus need to add the Google repository to their setup if they are not on an Android setup.
