### ISSUE TITLE
can't create keyset using tinkey and aws-kms in region other than us-east-1

### ISSUE THREAD

**Issue by k3vur** [google/tink#96]
I have an AWS-KMS Key that I can show using aws cli:

```
aws kms describe-key --key-id "<arn>"
```

However, when I do the following with tinkey, it fails:
```
./tinkey create-keyset --key-template AES256_GCM --out ~/Desktop/encrypted-keyset.cfg --master-key-uri "aws-kms://<arn>"
```

```
Exception in thread "main" java.security.GeneralSecurityException: encryption failed
	at com.google.crypto.tink.integration.awskms.AwsKmsAead.encrypt(AwsKmsAead.java:59)
	at com.google.crypto.tink.KeysetHandle.encrypt(KeysetHandle.java:107)
	at com.google.crypto.tink.KeysetHandle.write(KeysetHandle.java:98)
	at com.google.crypto.tink.tinkey.TinkeyUtil.writeKeyset(TinkeyUtil.java:204)
	at com.google.crypto.tink.tinkey.TinkeyUtil.createKeyset(TinkeyUtil.java:116)
	at com.google.crypto.tink.tinkey.CreateKeysetCommand.create(CreateKeysetCommand.java:48)
	at com.google.crypto.tink.tinkey.CreateKeysetCommand.run(CreateKeysetCommand.java:31)
	at com.google.crypto.tink.tinkey.Tinkey.main(Tinkey.java:42)
Caused by: com.amazonaws.services.kms.model.NotFoundException: Invalid arn (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: xxx)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:3036)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:3012)
	at com.amazonaws.services.kms.AWSKMSClient.executeEncrypt(AWSKMSClient.java:1366)
	at com.amazonaws.services.kms.AWSKMSClient.encrypt(AWSKMSClient.java:1342)
	at com.google.crypto.tink.integration.awskms.AwsKmsAead.encrypt(AwsKmsAead.java:57)
	... 7 more
```

What am I doing wrong?

edit:
I did the same using the Tink Java Library, and I think the problem is the included aws client tries to call `https://kms.us-east-1.amazonaws.com/`, although my key is located in eu-central-1. Can I tell tink to try eu-central-1?

**Comment by thaidn** [comment]
Thanks for the report.

@SalusaSecondus, you seem to work for AWS. Do you know what happened here? Thanks!

**Comment by SalusaSecondus** [comment]
@thaidn Glad to help here. I'm having some trouble navigating this project. Can you point me to where the AWSKMS client is actually constructed?  I'll still keep poking, but that would save me some time.

**Comment by thaidn** [comment]
Thanks SalusaSecondus!

The AWS client is in https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/awskms/AwsKmsClient.java.

**Comment by SalusaSecondus** [comment]
I ended up finding it. Thank you.

That construction will always point to a "default" region and in many cases that will just be "us-east-1". My recommendation is that you look at how we create clients in the `KmsMasterKeyProvider`  in the [aws-encryption-sdk-java](https://github.com/awslabs/aws-encryption-sdk-java).

Specific things which are likely to be helpful:
- [getStartingRegion](https://github.com/awslabs/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java#L566)
- Our use of the [client builder to spin off multiple clients for different regions](https://github.com/awslabs/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java#L253) (or with different credentials)

**Comment by thaidn** [comment]
Thanks SalusaSecondus.

While this looks easy to fix, and I'll fix it in our code, if the region is encoded in the key arn, why doesn't AWS KMS library automatically chooses the right region?

**Comment by SalusaSecondus** [comment]
Generally the Java clients are relatively thin and are configured to speak with exactly one region. Having one automatically figure out the proper region in general is a hard problem. This is made worse because not every call has an explicit region in it (unlike the encrypt call). How should the client behave then?

For calls without an explicit region, should it go to the configured one at creation or the region specified by the most recently used explicit region? Now when you make a bunch of calls, some might go to different regions, and thus the results won't properly work between the calls.  I agree that it causes confusion and can create issues, but we don't (currently) have a better way to handle this.  Our regions are very strongly isolated and we do require developers to know which region they are interacting with.

**Comment by thaidn** [comment]
Thanks for the explanation. For KMS the region is embedded in the key arn, thus I thought that it should be easy for the KMS client to figure out which region it should talk to. But what you said made me realize that this is KMS specific, and might not work for other services.

@kevur fixing this turns out is harder than expected because one of our existing clients is using a quite old version of AWS SDK. I'm upgrading them now, but it might take a few more days. Sorry for the delay!

**Comment by kevur** [comment]
@thaidn no problem or pressure whatsoever, I was able to have a hacky workaround for now (I'm on a groovy project, and groovy makes accessing the private AWSKMS client easier than it should be...). But thank you for your quick response and effort! Makes me more confident in having chosen google tink, and I look forward to not having to rely on said hacky hack.

**Comment by thaidn** [comment]
Thanks for choosing Tink. Just for your information, though Tink started as a personal project of the initial maintainers, we now have a dedicated team working full time on it (and Wycheproof). Our goal is to help everyone use crypto correctly everywhere. So if there's anything we can do, please let us know.

**Comment by thaidn** [comment]
Please use https://github.com/google/tink/releases/tag/v1.2.1 which should fix this issue. Sorry again for the long delay.
